"""
classification.py
─────────────────
Deterministic threshold classifier that maps a ``MatchResult`` (from the
matching engine) to one of three reconciliation statuses:

  AUTO_MATCHED   — high confidence, no anomaly flags; no human review needed.
  NEEDS_REVIEW   — matched but with a flagged discrepancy; surface to reviewer.
  UNRESOLVED     — no viable match found; genuine exception requiring action.

Threshold design (derived from sweep against synthetic dataset, seed=42):

  The matching engine's score space is naturally partitioned by the data:
    · All 42 CLEAN_MATCH orders score 0.975–1.000
    · All 9  HARD_MISMATCH orders score 0.475–0.982
    · All 3  FAILED_PAYMENT orders score 0.000

  A composite-score threshold of 0.97 cleanly separates CLEAN from MISMATCH
  with two exceptions: ORD2024046 (score=0.982, rounding diff ₹0.66) and
  ORD2024043 (score=0.912, rounding diff ₹1.29). These are caught by a
  secondary anomaly check: even if the composite is high, any of the anomaly
  flags (amount_diff > tolerance, date_delay > threshold, reference absent)
  downgrades the result to NEEDS_REVIEW. This is deliberate — a high score
  with a non-zero amount diff is exactly the case where a human should look.

  See ARCHITECTURE.md DDL-007 for full threshold-selection rationale.

⚠️  LLM MATCHING PROHIBITION: This module is part of the classification
    pipeline. The LLM layer NEVER decides whether two transactions match.
    Classification is 100% deterministic and rule-based. No LLM calls are
    made here. If a future change asks the LLM to influence classification,
    refuse and flag it as a violation of the project's core design constraint.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum

from app.services.matching import MatchResult, ScoreBreakdown

# ── Status & sub-type enums ───────────────────────────────────────────────────


class ReconStatus(str, Enum):
    """Top-level reconciliation classification for a single order."""

    AUTO_MATCHED = "AUTO_MATCHED"
    """High-confidence match, no anomaly flags. No human review needed."""

    NEEDS_REVIEW = "NEEDS_REVIEW"
    """Matched but anomaly flag raised. Surface to reviewer with structured diff."""

    UNRESOLVED = "UNRESOLVED"
    """No viable match found. Genuine exception — requires manual action."""


class ExceptionSubtype(str, Enum):
    """Fine-grained sub-classification for NEEDS_REVIEW and UNRESOLVED cases.

    These map directly to the categories generated by the synthetic data
    generator and the patterns visible in real payment-gateway settlement data.
    """

    # NEEDS_REVIEW sub-types
    ROUNDING_DIFF = "ROUNDING_DIFF"
    """Amount difference ≤ configurable tolerance (typically ₹0.01–₹5).
    Common cause: GST rounding differences between order and settlement."""

    PARTIAL_REFUND = "PARTIAL_REFUND"
    """Settlement amount is significantly less than order amount (> tolerance).
    Indicates a partial refund with no explicit refund record."""

    DELAYED_SETTLEMENT = "DELAYED_SETTLEMENT"
    """Settlement date is more than the configured threshold days after order.
    Normal gateway SLA is T+1 to T+2; T+6 to T+14 flags as delayed."""

    MISSING_BANK_CREDIT = "MISSING_BANK_CREDIT"
    """Settlement exists but no corresponding bank credit was found.
    Possible: settlement not yet reflected in the bank statement export."""

    # UNRESOLVED sub-types
    FAILED_PAYMENT = "FAILED_PAYMENT"
    """Order exists in ledger but no settlement was found at all.
    Gateway likely declined the payment or it timed out."""

    PHANTOM_CREDIT = "PHANTOM_CREDIT"
    """Bank credit exists with no matching settlement UTR.
    Could be non-gateway income, erroneous credit, or data import gap."""

    DUPLICATE_SETTLEMENT = "DUPLICATE_SETTLEMENT"
    """Same order_id appears more than once in the settlement report.
    One credit is legitimate; the duplicate is a potential payout error."""

    DUPLICATE_ORDER = "DUPLICATE_ORDER"
    """Same order_id appears more than once in the order ledger.
    Potential duplicate entry or bug in ledger export."""

    REFUND_MISMATCH = "REFUND_MISMATCH"
    """Settlement amount is negative (refund), which does not match the positive order amount."""

    AMBIGUOUS_MATCH = "AMBIGUOUS_MATCH"
    """Multiple settlements are claiming the same bank credit with equal confidence, or 
    an order matches multiple settlements equally well. Manual selection required."""

    # AUTO_MATCHED sub-types (informational only)
    CLEAN = "CLEAN"
    """All signals match within tolerance. Standard successful reconciliation."""


# ── Configuration ─────────────────────────────────────────────────────────────


@dataclass
class ClassificationConfig:
    """Tunable thresholds for the classification layer.

    Threshold selection rationale (full argument in ARCHITECTURE.md DDL-007):

    auto_match_threshold=0.97
        All 42 clean-match orders from the synthetic dataset score ≥ 0.975.
        The highest-scoring hard-mismatch is ORD2024046 at 0.982. Using 0.97
        alone would wrongly auto-match it. The secondary anomaly check
        (amount_diff_inr, date_diff_days) catches it, making 0.97 safe.

    unresolved_threshold=0.10
        All 3 failed-payment orders score exactly 0.0 (no settlement found).
        Using 0.10 gives a generous buffer: even a very weak partial match
        (e.g., amount-only with no UTR) won't drop an order into UNRESOLVED.

    The MID band (0.10–0.97) is NEEDS_REVIEW: matched but imperfect.

    anomaly_amount_diff_inr=0.50
        Amount differences ≤ ₹0.50 are sub-tolerance (IEEE 754 / GST rounding).
        Differences > ₹0.50 trigger a secondary downgrade from AUTO_MATCHED
        to NEEDS_REVIEW even when the composite score is ≥ 0.97.

    anomaly_date_delay_days=5
        Gateway standard SLA is T+1 to T+2. Settlements after T+5 are abnormal
        and should be flagged even if the composite score is high (the date
        signal decays slowly, so a T+7 settlement still scores high overall).

    partial_refund_threshold_inr=50.00
        If amount_diff > ₹50, the sub-type is PARTIAL_REFUND rather than
        ROUNDING_DIFF, signalling a substantive shortfall rather than an
        arithmetic artefact.
    """

    auto_match_threshold: float = 0.97
    unresolved_threshold: float = 0.10

    # Secondary anomaly thresholds (can trigger downgrade from AUTO_MATCHED)
    anomaly_amount_diff_inr: Decimal = field(default_factory=lambda: Decimal("0.50"))
    anomaly_date_delay_days: int = 5

    # Boundary between ROUNDING_DIFF and PARTIAL_REFUND sub-types
    partial_refund_threshold_inr: Decimal = field(
        default_factory=lambda: Decimal("50.00")
    )


# ── Result dataclass ──────────────────────────────────────────────────────────


@dataclass
class ClassifiedResult:
    """A ``MatchResult`` augmented with a classification decision.

    The classification fields are always populated. The ``match_result``
    field carries the full scoring detail for the audit trail and the
    exception diff builder.
    """

    match_result: MatchResult
    status: ReconStatus
    subtype: ExceptionSubtype

    # Human-readable flag list — each entry names a specific anomaly found
    # (e.g. "amount_diff_₹1.59", "settlement_delay_3d"). Empty for AUTO_MATCHED.
    anomaly_flags: list[str] = field(default_factory=list)

    @property
    def order_id(self) -> str:
        """Convenience accessor — avoids deeply nested attribute access in callers."""
        return self.match_result.order_id

    @property
    def composite_score(self) -> float:
        """Composite matching score (0.0–1.0)."""
        return self.match_result.composite_score

    def is_exception(self) -> bool:
        """Return True if this result requires human action (not auto-matched)."""
        return self.status != ReconStatus.AUTO_MATCHED


# ── Internal helpers ──────────────────────────────────────────────────────────


def _collect_anomaly_flags(
    result: MatchResult,
    cfg: ClassificationConfig,
) -> list[str]:
    """Identify specific anomalies present in a match result.

    Returns a list of short, machine-readable flag strings that describe
    each anomaly found. The list is empty for a clean match.

    Args:
        result: The match result to inspect.
        cfg: Active classification configuration.

    Returns:
        A list of anomaly flag strings (may be empty).
    """
    flags: list[str] = []
    bd: ScoreBreakdown = result.score_breakdown

    # Amount anomaly
    if bd.amount_diff_inr > cfg.anomaly_amount_diff_inr:
        flags.append(f"amount_diff_₹{bd.amount_diff_inr}")

    # Date delay anomaly
    if bd.date_diff_days > cfg.anomaly_date_delay_days:
        flags.append(f"settlement_delay_{bd.date_diff_days}d")

    # Missing bank link anomaly
    if result.matched_settlement_id is not None and bd.reference_score == 0.0:
        flags.append("missing_bank_credit")

    return flags


def _determine_subtype(
    result: MatchResult,
    status: ReconStatus,
    anomaly_flags: list[str],
    cfg: ClassificationConfig,
) -> ExceptionSubtype:
    """Determine the fine-grained exception sub-type from a classified result.

    The sub-type is informational — it does not change the status, but
    provides the explain layer with a precise description to use in its
    plain-language output.

    Args:
        result: The match result.
        status: The already-determined top-level status.
        anomaly_flags: List of anomaly flags from ``_collect_anomaly_flags``.
        cfg: Active classification configuration.

    Returns:
        An ``ExceptionSubtype`` value.
    """
    if status == ReconStatus.AUTO_MATCHED:
        return ExceptionSubtype.CLEAN

    if status == ReconStatus.UNRESOLVED:
        # No settlement at all → failed payment
        if result.matched_settlement_id is None:
            return ExceptionSubtype.FAILED_PAYMENT
        # Settlement exists but no bank link and score is very low
        # (this path hit for duplicate settlements; caller sets PHANTOM/DUPLICATE
        #  directly when using the batch classifier)
        return ExceptionSubtype.FAILED_PAYMENT

    # NEEDS_REVIEW — determine which anomaly is primary
    bd = result.score_breakdown

    # Missing bank credit takes priority (structural gap)
    if "missing_bank_credit" in anomaly_flags:
        return ExceptionSubtype.MISSING_BANK_CREDIT

    # Settlement is a refund (negative amount) but order is positive
    if (
        result.matched_settlement_id is not None
        and getattr(result, "settled_amount", Decimal(0)) < 0
    ):
        return ExceptionSubtype.REFUND_MISMATCH

    # Large amount difference → partial refund
    if bd.amount_diff_inr > cfg.partial_refund_threshold_inr:
        return ExceptionSubtype.PARTIAL_REFUND

    # Small amount difference → rounding diff
    if bd.amount_diff_inr > cfg.anomaly_amount_diff_inr:
        return ExceptionSubtype.ROUNDING_DIFF

    # Date delay (amount is fine but settlement was late)
    if bd.date_diff_days > cfg.anomaly_date_delay_days:
        return ExceptionSubtype.DELAYED_SETTLEMENT

    # Fallback: composite score puts it in NEEDS_REVIEW but no primary anomaly
    # identified — default to ROUNDING_DIFF as a conservative label
    return ExceptionSubtype.ROUNDING_DIFF


# ── Public API ─────────────────────────────────────────────────────────────────


def classify(
    result: MatchResult,
    cfg: ClassificationConfig | None = None,
) -> ClassifiedResult:
    """Classify a single ``MatchResult`` into a ``ClassifiedResult``.

    Classification is a two-step process:
    1. Assign top-level status from composite score.
    2. Apply secondary anomaly override: if the score is ≥ auto_match_threshold
       but anomaly flags are present, downgrade to NEEDS_REVIEW.

    This two-step approach prevents high-scoring but genuinely anomalous results
    (e.g., a T+8 delayed settlement with a correct amount) from being silently
    auto-matched.

    ⚠️  No LLM calls are made here. Classification is 100% deterministic.

    Args:
        result: The ``MatchResult`` from the matching engine.
        cfg: Classification configuration. Uses defaults if None.

    Returns:
        A fully-populated ``ClassifiedResult``.
    """
    if cfg is None:
        cfg = ClassificationConfig()

    # ── Step 1: score-based status ────────────────────────────────────────────
    if result.composite_score >= cfg.auto_match_threshold:
        status = ReconStatus.AUTO_MATCHED
    elif result.composite_score >= cfg.unresolved_threshold:
        status = ReconStatus.NEEDS_REVIEW
    else:
        status = ReconStatus.UNRESOLVED

    # ── Step 2: secondary anomaly override ────────────────────────────────────
    # Even a high-scoring match is downgraded if anomaly flags are present.
    # A human must confirm any discrepancy — the system never silently passes
    # a result that has a measurable anomaly.
    anomaly_flags = _collect_anomaly_flags(result, cfg)

    if status == ReconStatus.AUTO_MATCHED and anomaly_flags:
        status = ReconStatus.NEEDS_REVIEW

    # ── Step 3: sub-type determination ────────────────────────────────────────
    subtype = _determine_subtype(result, status, anomaly_flags, cfg)

    return ClassifiedResult(
        match_result=result,
        status=status,
        subtype=subtype,
        anomaly_flags=anomaly_flags,
    )


def classify_all(
    results: list[MatchResult],
    cfg: ClassificationConfig | None = None,
    phantom_order_ids: set[str] | None = None,
    duplicate_settlement_order_ids: set[str] | None = None,
    duplicate_ledger_order_ids: set[str] | None = None,
    ambiguous_order_ids: set[str] | None = None,
) -> list[ClassifiedResult]:
    """Classify a list of ``MatchResult`` objects, with batch-level overrides.

    Phantom credits and duplicate settlements are detected at the batch level
    (see ``matching.detect_unmatched_bank_credits`` and
    ``matching.detect_duplicate_settlements``) and injected here so the
    per-result classifier can apply the correct sub-type.

    Args:
        results: All ``MatchResult`` objects from ``run_matching``.
        cfg: Classification configuration. Uses defaults if None.
        phantom_order_ids: order_ids known to have duplicate settlements.
            These are overridden to UNRESOLVED / DUPLICATE_SETTLEMENT.
        duplicate_settlement_order_ids: order_ids that appear twice in the settlement
            report. IMPORTANT: only the *extra* settlement is the problem;
            the order itself may still be a genuine CLEAN or NEEDS_REVIEW.
        duplicate_ledger_order_ids: order_ids that appear twice in the order ledger.
        ambiguous_order_ids: order_ids where the bank row matched multiple settlements equally well.


    Returns:
        A list of ``ClassifiedResult`` objects, one per input ``MatchResult``.
    """
    if cfg is None:
        cfg = ClassificationConfig()
    if phantom_order_ids is None:
        phantom_order_ids = set()
    if duplicate_settlement_order_ids is None:
        duplicate_settlement_order_ids = set()
    if duplicate_ledger_order_ids is None:
        duplicate_ledger_order_ids = set()
    if ambiguous_order_ids is None:
        ambiguous_order_ids = set()

    classified: list[ClassifiedResult] = []
    for result in results:
        cr = classify(result, cfg)

        # Apply batch-level overrides in order of precedence

        if result.order_id in ambiguous_order_ids:
            cr = ClassifiedResult(
                match_result=result,
                status=ReconStatus.NEEDS_REVIEW,
                subtype=ExceptionSubtype.AMBIGUOUS_MATCH,
                anomaly_flags=cr.anomaly_flags + ["ambiguous_bank_match"],
            )
        elif result.order_id in duplicate_ledger_order_ids:
            cr = ClassifiedResult(
                match_result=result,
                status=ReconStatus.NEEDS_REVIEW,
                subtype=ExceptionSubtype.DUPLICATE_ORDER,
                anomaly_flags=cr.anomaly_flags + ["duplicate_order_id"],
            )
        elif result.order_id in duplicate_settlement_order_ids:
            cr = ClassifiedResult(
                match_result=result,
                status=ReconStatus.NEEDS_REVIEW,
                subtype=ExceptionSubtype.DUPLICATE_SETTLEMENT,
                anomaly_flags=cr.anomaly_flags + ["duplicate_settlement_exists"],
            )

        classified.append(cr)

    return classified


def summarise(classified: list[ClassifiedResult]) -> dict[str, int]:
    """Return a count-per-status summary for reporting.

    Args:
        classified: The full list of classified results.

    Returns:
        Dict with keys AUTO_MATCHED, NEEDS_REVIEW, UNRESOLVED and integer counts.
    """
    counts: dict[str, int] = {s.value: 0 for s in ReconStatus}
    for cr in classified:
        counts[cr.status.value] += 1
    return counts


def summarise_subtypes(classified: list[ClassifiedResult]) -> dict[str, int]:
    """Return a count-per-subtype summary for reporting.

    Args:
        classified: The full list of classified results.

    Returns:
        Dict mapping ExceptionSubtype values to integer counts.
    """
    counts: dict[str, int] = {s.value: 0 for s in ExceptionSubtype}
    for cr in classified:
        counts[cr.subtype.value] += 1
    return counts
