"""
exceptions.py
─────────────
GET /api/exceptions — sorted exception list with structured diffs.
GET /api/exceptions/{order_id}/explain — LLM explanation for one exception.

⚠️  LLM MATCHING PROHIBITION: The explain endpoint passes an already-classified
    ExceptionDiff to the LLM layer.  The LLM does not influence the match or
    classification decision.  It only generates a plain-language explanation of
    a decision already made by the deterministic pipeline.
"""

from __future__ import annotations

from fastapi import APIRouter, HTTPException

from app.api.schemas import (
    DiffEntrySchema,
    ExceptionListResponse,
    ExceptionSchema,
    ExplainResponse,
)
from app.api.state import app_state
from app.services.llm_layer import explain_exception

router = APIRouter(prefix="/api", tags=["exceptions"])


# ── Helper ────────────────────────────────────────────────────────────────────


def _serialise_diff_entry(e: object) -> DiffEntrySchema:
    """Convert a DiffEntry dataclass to its schema representation.

    Args:
        e: A DiffEntry instance from exception_diff.py.

    Returns:
        A DiffEntrySchema.
    """
    return DiffEntrySchema(
        field=e.field_name,  # type: ignore[attr-defined]
        expected=e.expected,  # type: ignore[attr-defined]
        actual=e.actual,  # type: ignore[attr-defined]
        delta=e.delta,  # type: ignore[attr-defined]
        signal=e.signal,  # type: ignore[attr-defined]
        weight=e.weight,  # type: ignore[attr-defined]
        score=round(e.score, 4),  # type: ignore[attr-defined]
        is_shortfall=e.is_shortfall,  # type: ignore[attr-defined]
    )


# ── Routes ────────────────────────────────────────────────────────────────────


@router.get(
    "/exceptions",
    response_model=ExceptionListResponse,
    summary="Exception list sorted by closeness to resolution",
    description=(
        "Returns all NEEDS_REVIEW and UNRESOLVED results from the last "
        "reconciliation run, sorted so that near-misses (highest composite "
        "score, smallest shortfall) appear first.  This surfaces the "
        "highest-value recoverable cases at the top of the review queue. "
        "Returns 409 if no run has been executed."
    ),
)
def list_exceptions() -> ExceptionListResponse:
    """Return the sorted exception list.

    Returns:
        An ExceptionListResponse with all non-AUTO_MATCHED results.

    Raises:
        HTTPException 409: If no reconcile run has been executed.
    """
    if not app_state.is_ready():
        raise HTTPException(
            status_code=409,
            detail="No reconciliation run found. Call POST /api/reconcile/run first.",
        )

    # exception_diffs are already sorted (build_exception_list sorts near-miss first)
    diffs = list(app_state.exception_diffs.values())

    items: list[ExceptionSchema] = [
        ExceptionSchema(
            order_id=d.order_id,
            status=d.status.value,
            subtype=d.subtype.value,
            composite_score=round(d.composite_score, 4),
            shortfall=round(d.shortfall, 4),
            anomaly_flags=d.anomaly_flags,
            has_candidate=d.has_candidate,
            resolution_hint=d.resolution_hint,
            entries=[_serialise_diff_entry(e) for e in d.entries],
        )
        for d in diffs
    ]

    return ExceptionListResponse(total=len(items), items=items)


@router.get(
    "/exceptions/{order_id}/explain",
    response_model=ExplainResponse,
    summary="LLM explanation for a single exception",
    description=(
        "Returns a plain-language explanation of why the specified order did not "
        "auto-match, written for a non-technical finance reviewer.  "
        "The explanation is generated by Gemini from the structured diff; it is "
        "cached in memory so re-requesting the same exception does not consume "
        "additional API quota.  "
        "The LLM does NOT re-classify or re-match the transaction.  "
        "Returns 404 if the order_id is not found or is AUTO_MATCHED.  "
        "Returns 409 if no run has been executed."
    ),
)
def explain_one_exception(order_id: str) -> ExplainResponse:
    """Generate (or return cached) LLM explanation for one exception.

    The diff object from the deterministic pipeline is the sole input to Gemini.
    If Gemini is unavailable, a structured fallback is returned without raising.

    Args:
        order_id: The order ID to explain.

    Returns:
        An ExplainResponse with the plain-language explanation and metadata.

    Raises:
        HTTPException 409: If no reconcile run has been executed.
        HTTPException 404: If the order_id is not found or is AUTO_MATCHED.
    """
    if not app_state.is_ready():
        raise HTTPException(
            status_code=409,
            detail="No reconciliation run found. Call POST /api/reconcile/run first.",
        )

    diff = app_state.get_exception(order_id)
    if diff is None:
        # Check if the order exists but is AUTO_MATCHED
        cr = app_state.get_classified(order_id)
        if cr is not None:
            raise HTTPException(
                status_code=404,
                detail=(
                    f"Order '{order_id}' is AUTO_MATCHED and has no exception diff. "
                    "Only NEEDS_REVIEW and UNRESOLVED orders can be explained."
                ),
            )
        raise HTTPException(
            status_code=404,
            detail=f"Order '{order_id}' not found in the current result set.",
        )

    # ── Call LLM layer (may return cached response or fallback) ───────────────
    llm_resp = explain_exception(diff)

    # Log the audit entry to app state so it appears in GET /api/audit-log
    app_state.add_audit_entry(llm_resp.audit_entry)

    return ExplainResponse(
        order_id=llm_resp.order_id,
        explanation=llm_resp.explanation,
        llm_status=llm_resp.llm_status,
        raw_diff=llm_resp.raw_diff,
        potential_hallucination=llm_resp.audit_entry.potential_hallucination,
        latency_ms=llm_resp.audit_entry.latency_ms,
    )
